package com.evocon.partnertracking.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommissionRuleSetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleSetAllPropertiesEquals(CommissionRuleSet expected, CommissionRuleSet actual) {
        assertCommissionRuleSetAutoGeneratedPropertiesEquals(expected, actual);
        assertCommissionRuleSetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleSetAllUpdatablePropertiesEquals(CommissionRuleSet expected, CommissionRuleSet actual) {
        assertCommissionRuleSetUpdatableFieldsEquals(expected, actual);
        assertCommissionRuleSetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleSetAutoGeneratedPropertiesEquals(CommissionRuleSet expected, CommissionRuleSet actual) {
        assertThat(actual)
            .as("Verify CommissionRuleSet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleSetUpdatableFieldsEquals(CommissionRuleSet expected, CommissionRuleSet actual) {
        assertThat(actual)
            .as("Verify CommissionRuleSet relevant properties")
            .satisfies(a ->
                assertThat(a.getCommissionRuleSetId()).as("check commissionRuleSetId").isEqualTo(expected.getCommissionRuleSetId())
            )
            .satisfies(a -> assertThat(a.getRuleSetName()).as("check ruleSetName").isEqualTo(expected.getRuleSetName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleSetUpdatableRelationshipsEquals(CommissionRuleSet expected, CommissionRuleSet actual) {
        // empty method
    }
}
