package com.evocon.partnertracking.domain;

import static com.evocon.partnertracking.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CommissionFeeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionFeeAllPropertiesEquals(CommissionFee expected, CommissionFee actual) {
        assertCommissionFeeAutoGeneratedPropertiesEquals(expected, actual);
        assertCommissionFeeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionFeeAllUpdatablePropertiesEquals(CommissionFee expected, CommissionFee actual) {
        assertCommissionFeeUpdatableFieldsEquals(expected, actual);
        assertCommissionFeeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionFeeAutoGeneratedPropertiesEquals(CommissionFee expected, CommissionFee actual) {
        assertThat(actual)
            .as("Verify CommissionFee auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionFeeUpdatableFieldsEquals(CommissionFee expected, CommissionFee actual) {
        assertThat(actual)
            .as("Verify CommissionFee relevant properties")
            .satisfies(a ->
                assertThat(a.getCommissionAmount())
                    .as("check commissionAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCommissionAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionFeeUpdatableRelationshipsEquals(CommissionFee expected, CommissionFee actual) {
        assertThat(actual)
            .as("Verify CommissionFee relationships")
            .satisfies(a -> assertThat(a.getLicense()).as("check license").isEqualTo(expected.getLicense()));
    }
}
