package com.evocon.partnertracking.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartnerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerAllPropertiesEquals(Partner expected, Partner actual) {
        assertPartnerAutoGeneratedPropertiesEquals(expected, actual);
        assertPartnerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerAllUpdatablePropertiesEquals(Partner expected, Partner actual) {
        assertPartnerUpdatableFieldsEquals(expected, actual);
        assertPartnerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerAutoGeneratedPropertiesEquals(Partner expected, Partner actual) {
        assertThat(actual)
            .as("Verify Partner auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerUpdatableFieldsEquals(Partner expected, Partner actual) {
        assertThat(actual)
            .as("Verify Partner relevant properties")
            .satisfies(a -> assertThat(a.getPartnerName()).as("check partnerName").isEqualTo(expected.getPartnerName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerUpdatableRelationshipsEquals(Partner expected, Partner actual) {
        // empty method
    }
}
